<a href="https://colab.research.google.com/github/Adarsh230305/Data_Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4])



In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a=(1,23,3)
print(a)

(1, 23, 3)


In [ ]:
# 2-array list
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l) # 2-d list
print(np.array(l)) # 2-d array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2-d zeros & ones

In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Linspace & arange method

#### Linespace is  used for equally spaceing between two number

In [ ]:
print("one elements btw 1 & 5: ",np.linspace(1,5,1))
print("two elements btw 1 & 5: ",np.linspace(1,5,2))
print("three elements btw 1 & : ",np.linspace(1,5,3))
print("five elements btw 1 & 5: ",np.linspace(1,5,5))
print("it can divide in small equal parts,like here in 10 equal part")
print(np.linspace(1,5,10))

one elements btw 1 & 5:  [1.]
two elements btw 1 & 5:  [1. 5.]
three elements btw 1 & :  [1. 3. 5.]
five elements btw 1 & 5:  [1. 2. 3. 4. 5.]
it can divide in small equal parts,like here in 10 equal part
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


#### arange is used to print the elments in particular range

In [ ]:
print(np.arange(1,5))

[1 2 3 4]


### Random generation function

In [ ]:
import numpy as np
print(np.random.rand(5)) # normalization (value will be btw 0-1)
print(np.random.randn(5)) # standarlization(values will be btw -3 to 3)
print(np.random.randint(1,100,10)) # generate 10 random integers btw 1 & 100

[0.82447367 0.55148303 0.54757026 0.21083495 0.30215792]
[ 0.51301105 -0.21912189  1.13394296 -1.23823065  0.22661049]
[59 38 73 59 12 88 54 54 59 63]


### array attributes

In [ ]:
ar=np.array([[1,2,3],[4,5,60],[7,8,9]])
print("shape:",ar.shape)
print("type",ar.dtype)
print("size",ar.size)

shape: (3, 3)
type int64
size 9


### array methods

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Min element: ",arr.min())
print("Max element: ",arr.max())
print("index of min element: ",arr.argmin())
print("index of max element: ",arr.argmax())
print("sum of array: ",arr.sum())
print("colomn wise sum: ",np.sum(arr,axis=0)) # coloumn wise sum
print("row wise sum: ",np.sum(arr,axis=1)) # row wise sum
print("mean: ",arr.mean())
print("standard deviation: ",arr.std())

Min element:  1
Max element:  9
index of min element:  0
index of max element:  8
sum of array:  45
colomn wise sum:  [12 15 18]
row wise sum:  [ 6 15 24]
mean:  5.0
standard deviation:  2.581988897471611


### reshaping array

In [ ]:
arr=np.arange(1,31)
print(arr)
k=arr.reshape(6,5)
print("Reshaped arr: \n",k)
p=arr.reshape(3,10) # size should be equal to the size of array
print("Reshaped arr: \n",p)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Reshaped arr: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Reshaped arr: 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


### array slicing & indexing

In [ ]:
import numpy as np
arr=np.arange(10,21)
print(arr)
k=arr[5] # indexing
print(k)
p=arr[5:10] # slicing
print(p)


[10 11 12 13 14 15 16 17 18 19 20]
15
[15 16 17 18 19]


### Numpy slicing and indexing of matrix

In [ ]:
arr=np.arange(1,31).reshape(6,5)
print("array:\n",arr)
print("slicing of array")
print("row wise slicing: ",arr[1]) # row wise
print("element at 1,4 index: ",arr[1,4]) # particular element at position (1,4)
print("slice of matrix: \n",arr[1:4,2:4]) # it will slice a matrix from row index(1,4) & column index(2,4)
print(arr[4:,3:])
print("slice 3rd column: ",arr[:,3])

array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
slicing of array
row wise slicing:  [ 6  7  8  9 10]
element at 1,4 index:  10
slice of matrix: 
 [[ 8  9]
 [13 14]
 [18 19]]
[[24 25]
 [29 30]]
slice 3rd column:  [ 4  9 14 19 24 29]


### Boolean Indexing

In [ ]:
arr=np.arange(1,11)
print(arr)
bool_index=arr%2==0 # it will slice the array with even numbers only
print(bool_index)
print(arr[bool_index])  # sliced array with even number

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


### Array operations

#### arithematic operation

In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2)
print(a1**a2)
print(a1%a2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[    1    64  2187 65536]
[1 2 3 4]


#### broadcasting

In [ ]:
l=[1,2,3,4]
k=np.array(l)
# print(l+10) will throw an error
print(k+10)

[11 12 13 14]


### Deep copy & shallow copy

In [ ]:
# shallow copy :when we changes in its slice the orignal array don't get changed
arr=np.arange(1,11)
print(arr)
slice_array=arr[:5]
print(slice_array+10)
print("orignal array remain same: ",arr)
# deep copy :when we changes in its slcie the orignal array get changed
# slicing se shallow copy banta hai but agr hm pura array hi copy kr lete hai  to deep copy bn jata hai
b=arr
b[0]=100
print("b: ",b)
print("Now the orignal array changed",arr)
# but we can change our deep copy to shallow copy using copy()
b=arr.copy()
b[0]=105
print("b: ",b)
print("Now the orignal array remain same",arr)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15]
orignal array remain same:  [ 1  2  3  4  5  6  7  8  9 10]
b:  [100   2   3   4   5   6   7   8   9  10]
Now the orignal array changed [100   2   3   4   5   6   7   8   9  10]
b:  [105   2   3   4   5   6   7   8   9  10]
Now the orignal array remain same [100   2   3   4   5   6   7   8   9  10]


### matrix operations

#### Matrix multiplication (additon & sub remain same as in vectors)

In [ ]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[4,5],[6,7]])
print(m1*m2) # element wise multiplication
print(m1@m2) # matrix multiplication or print(np.dot(m1,m2))
print(np.dot(m1,m2))

[[ 4 10]
 [18 28]]
[[16 19]
 [36 43]]
[[16 19]
 [36 43]]


#### Transpose of matrix

In [ ]:
m1=np.array([[1,2,3],[4,5,6]])
print(m1)
print("tranpose of matrix: \n",m1.T)

[[1 2 3]
 [4 5 6]]
tranpose of matrix: 
 [[1 4]
 [2 5]
 [3 6]]


### Advance array manipulation

#### Stacking of array
##### note: matrix can not be stacked ,we can stack a vector only

In [ ]:
a1=np.arange(1,6)
a2=np.arange(6,11)
print(a1)
print(a2)
print("Vetrical Stack: \n",np.vstack((a1,a2)))
print("Horizontal Stack: \n",np.hstack((a1,a2)))
print("Column wise Stack: \n",np.column_stack((a1,a2)))

[1 2 3 4 5]
[ 6  7  8  9 10]
Vetrical Stack: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontal Stack: 
 [ 1  2  3  4  5  6  7  8  9 10]
Column wise Stack: 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


#### Spliting of matrix

In [ ]:
ar=np.arange(16).reshape(4,4)
print(ar)
print("vertical spliting: \n",np.vsplit(ar,2)) # split array in two equal parts vertically
print("horizontal spliting: \n",np.hsplit(ar,2)) # split array in two equal parts horizont


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
vertical spliting: 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
horizontal spliting: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### Exercise

#### valid sudoku

In [ ]:
import numpy as np

sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
print("sudoku: \n",sudoku)
sum1=np.sum(sudoku,axis=1) # row wise sum
print("row wise sum: ",sum1)
sum2=np.sum(sudoku,axis=0) # coloumn wise sum
print("coloumn wise sum: ",sum2)
for i in sum1:
  if i!=45:
    print("Invalid sudoku")
    break
else:
  for i in sum2:
    if i!=45:
      print("Invalid sudoku")
      break
  else:
    for i in range(0,9,3):
      for j in range(0,9,3):
        sum3=sudoku[i:i+3,j:j+3].sum()
        if sum3!=45:
         print("Invalid sudoku")
         break
    else :
      print("valid sudoku")
print(np.mean(sudoku[:,0],axis=0))


sudoku: 
 [[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
row wise sum:  [45 45 45 45 45 45 45 45 45]
coloumn wise sum:  [45 45 45 45 45 45 45 45 45]
valid sudoku
5.0
